"""init all entities

Revision ID: 602768f5b69d
Revises:
Create Date: 2026-08-21 05:41:30.259293+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "602768f5b69d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostGIS 必须先于一切空间表存在（装在 public，各 dev schema 共用，
    # 见 docs/DEV_SETUP.md §5）。若目标库已装则此句是 no-op。
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_accounts",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_accounts")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_accounts_username")),
        schema="dev_limpid",
    )
    op.create_table(
        "themes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column(
            "assets",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_themes")),
        schema="dev_limpid",
    )
    op.create_table(
        "thought_tags",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thought_tags")),
        schema="dev_limpid",
    )
    op.create_table(
        "users",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        schema="dev_limpid",
    )
    op.create_index(
        op.f("ix_users_device_id"), "users", ["device_id"], unique=True, schema="dev_limpid"
    )
    op.create_geospatial_table(
        "letters",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("poem", sa.Text(), nullable=True),
        sa.Column(
            "images",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("theme", sa.String(length=32), server_default=sa.text("'natsu'"), nullable=False),
        sa.Column("music_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "location",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("place_label", sa.String(length=128), nullable=True),
        sa.Column("weather", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delivery_mode", sa.Enum("stay", "drift", name="delivery_mode"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "public", "rejected", "taken_down", name="letter_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("parent_letter_id", sa.UUID(), nullable=True),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("resonance_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("voice_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reply_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("saved_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(content) <= 800", name=op.f("ck_letters_content_max_len")),
        sa.CheckConstraint("jsonb_array_length(images) <= 3", name=op.f("ck_letters_images_max_3")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["dev_limpid.users.id"],
            name=op.f("fk_letters_owner_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_letters_parent_letter_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_letters")),
        schema="dev_limpid",
    )
    op.create_geospatial_index(
        "idx_letters_location",
        "letters",
        ["location"],
        unique=False,
        schema="dev_limpid",
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "ix_letters_owner",
        "letters",
        ["owner_user_id", sa.literal_column("created_at DESC")],
        unique=False,
        schema="dev_limpid",
    )
    op.create_index(
        "ix_letters_parent", "letters", ["parent_letter_id"], unique=False, schema="dev_limpid"
    )
    op.create_index(
        "ix_letters_pool", "letters", ["status", "delivery_mode"], unique=False, schema="dev_limpid"
    )
    op.create_table(
        "letter_reads",
        sa.Column("letter_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_letter_reads_letter_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dev_limpid.users.id"],
            name=op.f("fk_letter_reads_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("letter_id", "user_id", name=op.f("pk_letter_reads")),
        schema="dev_limpid",
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("reply", name="notification_type"), nullable=False),
        sa.Column("letter_id", sa.UUID(), nullable=False),
        sa.Column("parent_letter_id", sa.UUID(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_notifications_letter_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_notifications_parent_letter_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dev_limpid.users.id"],
            name=op.f("fk_notifications_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        schema="dev_limpid",
    )
    op.create_index(
        "ix_notifications_inbox",
        "notifications",
        ["user_id", "is_read"],
        unique=False,
        schema="dev_limpid",
    )
    op.create_table(
        "reports",
        sa.Column("letter_id", sa.UUID(), nullable=False),
        sa.Column("reporter_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_reports_letter_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["dev_limpid.users.id"],
            name=op.f("fk_reports_reporter_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        schema="dev_limpid",
    )
    op.create_table(
        "resonance_logs",
        sa.Column("letter_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.String(length=30), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_resonance_logs_letter_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dev_limpid.users.id"],
            name=op.f("fk_resonance_logs_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resonance_logs")),
        sa.UniqueConstraint("letter_id", "user_id", name="uq_resonance_once"),
        schema="dev_limpid",
    )
    op.create_table(
        "scripbook_entries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("letter_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["dev_limpid.letters.id"],
            name=op.f("fk_scripbook_entries_letter_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["dev_limpid.users.id"],
            name=op.f("fk_scripbook_entries_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "letter_id", name=op.f("pk_scripbook_entries")),
        schema="dev_limpid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scripbook_entries", schema="dev_limpid")
    op.drop_table("resonance_logs", schema="dev_limpid")
    op.drop_table("reports", schema="dev_limpid")
    op.drop_index("ix_notifications_inbox", table_name="notifications", schema="dev_limpid")
    op.drop_table("notifications", schema="dev_limpid")
    op.drop_table("letter_reads", schema="dev_limpid")
    op.drop_index("ix_letters_pool", table_name="letters", schema="dev_limpid")
    op.drop_index("ix_letters_parent", table_name="letters", schema="dev_limpid")
    op.drop_index("ix_letters_owner", table_name="letters", schema="dev_limpid")
    op.drop_geospatial_index(
        "idx_letters_location",
        table_name="letters",
        schema="dev_limpid",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_geospatial_table("letters", schema="dev_limpid")
    op.drop_index(op.f("ix_users_device_id"), table_name="users", schema="dev_limpid")
    op.drop_table("users", schema="dev_limpid")
    op.drop_table("thought_tags", schema="dev_limpid")
    op.drop_table("themes", schema="dev_limpid")
    op.drop_table("admin_accounts", schema="dev_limpid")
    # ### end Alembic commands ###
